[project]
name = "predicta-ai-football"
version = "2.0.0"
description = "Süper Öğrenen Yapay Zeka Futbol Tahmin Sistemi"
readme = "README.md"
requires-python = ">=3.8"  # Daha geniş Python desteği
keywords = ["football", "ai", "machine-learning", "predictions", "sports"]
authors = [
    {name = "Predicta AI Team", email = "ai@predicta.com"}
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    "Topic :: Scientific/Engineering :: Information Analysis"
]

dependencies = [
    # ==================== 🤖 AI & MACHINE LEARNING ====================
    "scikit-learn>=1.3.0",
    "joblib>=1.2.0",
    "scipy>=1.11.0",
    "threadpoolctl>=3.0.0",
    
    # ==================== 📊 VERI İŞLEME & ANALIZ ====================
    "beautifulsoup4>=4.12.2",
    "numpy>=1.24.3",  # Daha kararlı versiyon
    "pandas>=2.0.3",  # Daha kararlı versiyon
    "plotly>=5.18.0",
    "requests>=2.31.0",

    # ==================== 🌐 WEB SERVIS & API ====================
    "fastapi>=0.104.1",
    "uvicorn[standard]>=0.24.0",
    "jinja2>=3.1.2",
    
    # ==================== 📈 İSTEĞE BAĞLI GÖRSELLEŞTİRME ====================
    "streamlit>=1.29.0",
    
    # ==================== 🔧 YARDIMCI KÜTÜPHANELER ====================
    "python-multipart>=0.0.6",
    "python-dateutil>=2.8.2",
    "pytz>=2023.3",
    "unidecode>=1.3.7"
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0",
    "black>=23.0.0",
    "flake8>=6.0.0",
]

ml = [
    "matplotlib>=3.7.0",
    "seaborn>=0.12.0",
]

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

# ==================== 🤖 AI MODEL KONFİGÜRASYONU ====================
[tool.predicta.ai]
model_version = "2.0.0"
min_confidence = 65.0
training_samples_min = 50
feature_count = 30

[tool.black]
target-version = ['py38']  # Daha geniş Python desteği
line-length = 88
