services:
  - type: web
    name: predicta-ai-fastapi
    env: python
    plan: free
    region: frankfurt  # Frankfurt region (daha stabil)
    buildCommand: |
      echo "🚀 Predicta AI Sistemi Kuruluyor..."
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      echo "✅ Bağımlılıklar kuruldu"
      mkdir -p data/ai_models_v2
      echo "🤖 AI Model klasörü hazır"
      python update_database.py
      python create_models_folder.py
    startCommand: |
      echo "🎯 Predicta AI Başlatılıyor..."
      uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0  # Daha kararlı Python versiyonu
      - key: PORT
        value: 10000
      - key: SECRET_KEY
        generateValue: true
      - key: AI_MODEL_PATH
        value: data/ai_models_v2
      - key: LOG_LEVEL
        value: INFO
      - key: AI_TRAINING_SAMPLES_MIN
        value: 50
      - key: AI_CONFIDENCE_THRESHOLD
        value: 65.0

    # Health Check Path
    healthCheckPath: /health

    # Auto-Deploy ayarları
    autoDeploy: true

    # Build ve deploy için optimize ayarlar
    buildFilter:
      branches:
        only: [main, master]
